# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JobVariety' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobVariety

  target 'JobVarietyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'JobVariety-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobVariety-tvOS

  target 'JobVariety-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
